// <auto-generated />
using System;
using CarAssemblyErp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarAssemblyErp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.BomNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentPartId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChildPartId");

                    b.HasIndex("ParentPartId", "ChildPartId")
                        .IsUnique();

                    b.ToTable("BomNodes", t =>
                        {
                            t.HasCheckConstraint("CK_BomNode_NoSelfRef", "\"ParentPartId\" <> \"ChildPartId\"");

                            t.HasCheckConstraint("CK_BomNode_Quantity", "\"Quantity\" > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            ChildPartId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ParentPartId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ChildPartId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ParentPartId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            ChildPartId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ParentPartId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            ChildPartId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ParentPartId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ChildPartId = new Guid("55555555-5555-5555-5555-555555555555"),
                            ParentPartId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 12
                        });
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RunningBalance")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.ToTable("InventoryTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_InventoryTransaction_Quantity", "\"Quantity\" <> 0");
                        });
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SafetyStock")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Specification")
                        .HasColumnType("text");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("IX_Part_Sku")
                        .HasAnnotation("Npgsql:IndexExpression", "LOWER(\"Sku\")");

                    b.ToTable("Parts", t =>
                        {
                            t.HasCheckConstraint("CK_Part_SafetyStock", "\"SafetyStock\" >= 0");

                            t.HasCheckConstraint("CK_Part_StockQuantity", "\"StockQuantity\" >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "底盘",
                            SafetyStock = 5,
                            Sku = "CHASSIS-001",
                            Specification = "标准底盘",
                            StockQuantity = 10,
                            Unit = "个"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "轮胎",
                            SafetyStock = 20,
                            Sku = "TIRE-001",
                            Specification = "标准轮胎",
                            StockQuantity = 100,
                            Unit = "个"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "引擎",
                            SafetyStock = 2,
                            Sku = "ENGINE-001",
                            Specification = "V6引擎",
                            StockQuantity = 5,
                            Unit = "个"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "活塞",
                            SafetyStock = 10,
                            Sku = "PISTON-001",
                            Specification = "标准活塞",
                            StockQuantity = 20,
                            Unit = "个"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "螺丝",
                            SafetyStock = 100,
                            Sku = "SCREW-001",
                            Specification = "M8螺丝",
                            StockQuantity = 500,
                            Unit = "个"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "整车",
                            SafetyStock = 1,
                            Sku = "CAR-001",
                            Specification = "标准轿车",
                            StockQuantity = 0,
                            Unit = "辆"
                        });
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetPartId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkstationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("TargetPartId");

                    b.HasIndex("WorkstationId");

                    b.ToTable("ProductionOrders", t =>
                        {
                            t.HasCheckConstraint("CK_ProductionOrder_CompletedQuantity", "\"CompletedQuantity\" >= 0 AND \"CompletedQuantity\" <= \"Quantity\"");

                            t.HasCheckConstraint("CK_ProductionOrder_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.Workstation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Workstations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            IsActive = true,
                            Location = "车间1",
                            Name = "总装线A"
                        });
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.BomNode", b =>
                {
                    b.HasOne("CarAssemblyErp.Domain.Entities.Part", "ChildPart")
                        .WithMany()
                        .HasForeignKey("ChildPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarAssemblyErp.Domain.Entities.Part", "ParentPart")
                        .WithMany()
                        .HasForeignKey("ParentPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildPart");

                    b.Navigation("ParentPart");
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("CarAssemblyErp.Domain.Entities.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("CarAssemblyErp.Domain.Entities.ProductionOrder", b =>
                {
                    b.HasOne("CarAssemblyErp.Domain.Entities.Part", "TargetPart")
                        .WithMany()
                        .HasForeignKey("TargetPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarAssemblyErp.Domain.Entities.Workstation", "Workstation")
                        .WithMany()
                        .HasForeignKey("WorkstationId");

                    b.Navigation("TargetPart");

                    b.Navigation("Workstation");
                });
#pragma warning restore 612, 618
        }
    }
}
